config/routes.rb
Rails.application.routes.draw do
  root "employees#index"

  resource :users, except: [:new, :destroy] do 
    get :sign_up
    get :sign_in
  end

  resource :sessions, only: [:create, :destroy]

  resources :clients, except: [:destroy]

  resources :records, except: [:index, :destroy]

  resources :employees, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :records
  belongs_to :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :clients
  belongs_to :role
  belongs_to :user

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/record.rb
class Record < ApplicationRecord
  has_many :clients
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :employees
end

app/models/user.rb
class User < ApplicationRecord
  has_one :employee

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}, confirmation: true

  before_create :encrypt_password

  def self.login(user_params)
    email = user_params[:email]
    password = user_params[:password]

    hashed_password = Digest::SHA1.hexdigest("xx-#{password}-yy")

    find_by(email: email, password: hashed_password)
  end

  private
  
  def encrypt_password
    # salting
    pw = "xx-#{self.password}-yy"
    self.password = Digest::SHA1.hexdigest(pw)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?

  private

  def record_not_found
    render file: "#{Rails.root}/public/404.html",
           layout: false,
           status: 404
  end

  # 記憶 memorization
  def current_user
    @_user ||= User.find_by(id: session[:user_session])
  end

  def user_signed_in?
    session[:user_session] && current_user
  end

  def authenticate_user!
    redirect_to sign_in_users_path if not user_signed_in?
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_client, only: [:show, :edit, :update]
  
  def index
    @clients = Client.all
  end
  
  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: "客戶資料建立完成！"
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @client.update(client_params)
      redirect_to clients_path, notice: "客戶資料修改完成"
    else
      render :edit
    end
  end

  private
  def client_params
    params.require(:client).permit(:name, :email, :tel, :add, :note)
  end
  
  def find_client
    @client = Client.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_employee, only: [:show, :edit, :update]
  
  def index
    @employees = Employee.all
  end
  
  def new
    @employee = Employee.new
  end
  
  def create
    @employee = @_user.build_employee(employee_params)
    if @employee.save
      redirect_to employees_path, notice: "員工資料建立完成！"
    else
      render :new
    end
  end
  
  def show 
  end
  
  def edit
  end
  
  def update
    if @employee.update(employee_params)
      redirect_to employees_path, notice: "員工資料修改完成"
    else
      render :edit
    end
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :email)
  end
  
  def find_employee
    @employee = Employee.find(params[:id])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_record, only: [:show, :edit, :update]
  
  def new
    @record = Record.new
  end
  
  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to clients_path, notice: "訪視資料建立完成！"
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @record.update(record_params)
      redirect_to clients_path, notice: "訪視資料修改完成"
    else
      render :edit
    end
  end

  private
  def record_params
    params.require(:record).permit(:name, :email, :tel, :add, :note)
  end
  
  def find_record
    @record = record.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.login(params[:user])

    if user
      # 發號碼牌 發 session
      session[:user_session] = user.id
      if user.employee.present?
        redirect_to "/", notice: "登入成功"
      else
        redirect_to new_employee_path, notice: "請先建立員工資料"
      end
    else
      redirect_to "/users/sign_in", notice: "登入失敗"
    end
  end

  def destroy
    session[:user_session] = nil
    redirect_to root_path, notice: "已登出"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def sign_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to "/", notice: "會員註冊成功"
    else
      render :sign_up
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<% if client.errors.any? %>
  <ul>
    <% client.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for client do |form| %>
  <div>
    客戶姓名：<%= form.text_field :name %>
  </div>

  <div>
    電話：<%= form.text_field :tel %>
  </div>

  <div>
    Email：<%= form.text_field :email %>
  </div>

  <div>
    通訊地址：<%= form.text_field :add %>
  </div>

  <div>
    備註：<%= form.text_area :note %>
  </div>

  <%= form.submit %>
<% end %>

app/views/clients/edit.html.erb
<h1>修改客戶資料</h1>

<%= render "form", client: @client %>

app/views/clients/index.html.erb
<h1>客戶列表</h1>
<%= link_to "員工列表", new_client_path %>
<%= link_to "新增客戶資料", new_client_path %>

<table>
  <thead>
    <tr>
      <td>客戶姓名</td>
      <td>客戶Email</td>
    </tr>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= link_to client.name, client %></td>
          <td><%= client.email %></td>
          <td><%= link_to "修改客戶資料", edit_client_path(client) %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>

</table>

app/views/clients/new.html.erb
<h1>新增客戶資料</h1>

<%= render "form", client: @client %>

app/views/clients/show.html.erb
<h2><%= @client.name %></h2>
<ul>
  <li><%= @client.tel %></li>
  <li><%= @client.email %></li>
  <li><%= @client.add %></li>
  <li><%= @client.note %></li>
</ul>
<%= link_to "新增訪視紀錄", new_record_path %>

app/views/employees/_form.html.erb
<% if employee.errors.any? %>
  <ul>
    <% employee.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for employee do |form| %>
  <div>
    員工姓名：<%= form.text_field :name %>
  </div>

  <div>
    Email：<%= form.text_field :email %>
  </div>

  <div>
    身份：<%= form.select :role_id, Role.all.map{ |r| [r.name, r.id] }, {}, :class => "form-control" %>
  </div>

  <%= form.submit %>
<% end %>

app/views/employees/edit.html.erb
<h1>修改員工資料</h1>

<%= render "form", employee: @employee %>

app/views/employees/index.html.erb
<h1>員工列表</h1>

<%= link_to "新增員工資料", new_employee_path %>
<table>
  <thead>
    <tr>
      <td>員工編號</td>
      <td>員工姓名</td>
      <td>員工Email</td>
    </tr>
    <tbody>
      <% @employees.each do |emp| %>
        <tr>
          <td><%= link_to emp.emp_no, emp %></td>
          <td><%= emp.name %></td>
          <td><%= emp.email %></td>
          <td><%= link_to "修改員工資料", edit_employee_path(emp) %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>

</table>

app/views/employees/new.html.erb
<h1>新增員工資料</h1>

<%= render "form", employee: @employee %>

app/views/employees/show.html.erb
<ul>
  <h2><%= @employee.name %></h2>
  <h2><%= @employee.email %></h2>
  <h2><%= @employee.emp_no %></h2>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonnelManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="flex">
        <li><%= current_user.email %></li>
        <li><%= link_to "登出", sessions_path, method: "delete" %></li>
      </div>
    <% else %>
      <div>
        <li><%= link_to "首頁", "/" %></li>
      </div>
      <div class="flex">
        <li><%= link_to "登入", sign_in_users_path %></li>
        <li><%= link_to "註冊", sign_up_users_path %></li>
      </div>
    <% end %>

    <span><%= notice %></span>
    <%= yield %>
  </body>
</html>

app/views/records/_form.html.erb
<% if record.errors.any? %>
  <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for record do |form| %>
  <div>
    紀錄標題：<%= form.text_field :title %>
  </div>

  <div>
    紀錄：<%= form.text_area :description %>
  </div>

  <div>
    開始訪視時間：
  </div>

  <div>
    結束訪視時間：
  </div>

  <%= form.submit %>
<% end %>

app/views/records/edit.html.erb
<h1>修改訪視紀錄</h1>

<%= render "form", record: @record %>

app/views/records/new.html.erb
<h1>新增訪視紀錄</h1>

<%= render "form", record: @record %>

app/views/records/show.html.erb
<h2><%= @record.title %></h2>
<ul>
  <li>紀錄：<%= @record.description %></li>
  <li>開始訪視時間：<%= @record.start_at %></li>
  <li>結束訪視時間<%= @record.end_at %></li>
</ul>

app/views/users/sign_in.html.erb
<h1>登入</h1>

<%= form_with model: @user, url: sessions_path do |form| %>
  <div>
    <%= form.label :email, "Email" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password, "密碼" %>
    <%= form.password_field :password %>
  </div>
  <%= form.submit "登入" %>
<% end %>

app/views/users/sign_up.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :email, "Email" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password, "密碼" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation, "密碼確認" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit "註冊" %>
<% end %>